<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http:///model.ecore" nsPrefix="model">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="Model"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Author:taras.&#xA;Created:11/17/17 12:42 PM.&#xA;Title:.&#xA;Comment:.&#xA;"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TestDIagram">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Test DIagram"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Coffee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coffeineValue" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volume" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coffee" ordered="false"
        lowerBound="1" eType="#//Coffee"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="water" ordered="false"
        lowerBound="1" eType="#//Water"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Water">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temperature" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clean" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eSubpackages name="umlStandardProfile" nsURI="http:///model/umlStandardProfile.ecore"
      nsPrefix="model.umlStandardProfile">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="UML Standard Profile"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="UML Standard Profile contains a UML metamodel (metaclasses without properties and associations), Standard UML stereotypes defined in the annex C of UML specification, validation suites for UML model correctness and completeness checking, and stereotypes used by MagicDraw internally."/>
    </eAnnotations>
  </eSubpackages>
</ecore:EPackage>
